export const jsonRight = {
  applicationId: 'APP101676',
  cancellationApplicationId: null,
  cancellationDocuments: [],
  cancellationNotationText: null,
  cancellationReason:
    'cancelling title since duplicate primary rrrs created due to invalid configuration',
  cancelledDate: '2023-08-11T05:26:57',
  createdDate: '2023-07-20T12:48:42',
  customMetadata: [
    {
      id: '1e8a8cfe-11e7-4e05-b388-bbd4dc9e07ef',
      metadata: { textField: null },
    },
  ],
  description: 'test',
  documents: [],
  id: '0a000321-8972-1c6c-8189-73586c880005',
  lastModifiedDate: '2023-08-11T05:26:57',
  legalFramework: 'Fee simple Register',
  notationText: null,
  parcelGeneratedId: ['PID13480'],
  parentTitleIds: ['TID0338'],
  registeredDate: '2023-07-20T11:56:28',
  rrrs: [
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: null,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Agreement between the first party and the second party for this registration entry',
          documentId: 'DOC0394',
          documentType: 'Agreement',
          expiryDate: '2001-06-13',
          id: '52d5a8f5-c2e6-40ed-9ecc-c56bfbb99b0a',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'EJ/83/7168',
          signedDate: '1986-08-02',
          sourceAgency: 'GBON & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '2.7',
        },
      ],
      effectiveDate: null,
      expiryDate: null,
      id: '1a4242d7-908c-42f7-8ea5-7fded63a791c',
      isPrimary: false,
      lease: null,
      mortgage: null,
      notationText:
        'Registration of Grazing Right in the name of Sun Life Financial , Miami . Supporting documents: DOC0394.',
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2764',
      rrrName: 'Grazing Right',
      rrrParties: [
        {
          id: '4fde96cc-0248-40a6-89ab-baffe6436e53',
          parties: [
            {
              address: {
                address1: '105 Wapiti Close',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 1E9',
                state: 'AB',
              },
              customMetadata: [],
              dob: null,
              email: 'sunlifefinancial@lac.gmail.com',
              familyName: null,
              forename: 'Sun Life Financial',
              gender: null,
              idReference: null,
              idType: 'National ID',
              partyId: 'PAR0439',
              partyType: 'Organisation',
              phone: '+1 506 0472760',
              profession: null,
              referenceNo: '18-708-2530',
              role: ['Agent', 'Multicipality', 'Attorney'],
            },
            {
              address: {
                address1: '229A Three Sisters Drive',
                address2: 'Road 2',
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 0A1',
                state: 'AB',
              },
              customMetadata: [
                {
                  id: '32efdc95-ac9d-4239-82d7-95a94a8a4870',
                  metadata: { placeOfBirth: 'Jodon', serialNumber: null },
                },
              ],
              dob: null,
              email: 'matrox@lac.gmail.com',
              familyName: null,
              forename: 'Miami',
              gender: null,
              idReference: null,
              idType: 'Company Registration',
              partyId: 'PAR0297',
              partyType: 'Organisation',
              phone: '+1 506 4703912',
              profession: null,
              referenceNo: '95-670-72',
              role: ['Applicant'],
            },
          ],
          share: null,
        },
      ],
      status: 'CURRENT',
    },
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: 100,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Contract between the first party and the second party for the purchase of this property',
          documentId: 'DOC0265',
          documentType: 'Contract for Sale',
          expiryDate: '1958-09-28',
          id: '39cb1437-8bee-4e5d-ad7a-5c965e45bea8',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'VB/76/7677',
          signedDate: '1949-09-08',
          sourceAgency: 'CBIH & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '1.0',
        },
      ],
      effectiveDate: null,
      expiryDate: null,
      id: 'af020f43-ad2a-4688-8219-5f7ae3dd06fb',
      isPrimary: true,
      lease: null,
      mortgage: null,
      notationText:
        'Transfer of Strata ownership to Sun Life Financial , Miami . Declared value of £100.00. Supporting documents: DOC0265.',
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2797',
      rrrName: 'Strata',
      rrrParties: [
        {
          id: '62b39eb3-7741-4b42-b386-f797aee24df2',
          parties: [
            {
              address: {
                address1: '229A Three Sisters Drive',
                address2: 'Road 2',
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 0A1',
                state: 'AB',
              },
              customMetadata: [
                {
                  id: '32efdc95-ac9d-4239-82d7-95a94a8a4870',
                  metadata: { placeOfBirth: 'Jodon', serialNumber: null },
                },
              ],
              dob: null,
              email: 'matrox@lac.gmail.com',
              familyName: null,
              forename: 'Miami',
              gender: null,
              idReference: null,
              idType: 'Company Registration',
              partyId: 'PAR0297',
              partyType: 'Organisation',
              phone: '+1 506 4703912',
              profession: null,
              referenceNo: '95-670-72',
              role: ['Applicant'],
            },
            {
              address: {
                address1: '105 Wapiti Close',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 1E9',
                state: 'AB',
              },
              customMetadata: [],
              dob: null,
              email: 'sunlifefinancial@lac.gmail.com',
              familyName: null,
              forename: 'Sun Life Financial',
              gender: null,
              idReference: null,
              idType: 'National ID',
              partyId: 'PAR0439',
              partyType: 'Organisation',
              phone: '+1 506 0472760',
              profession: null,
              referenceNo: '18-708-2530',
              role: ['Agent', 'Multicipality', 'Attorney'],
            },
          ],
          share: null,
        },
      ],
      status: 'CURRENT',
    },
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: 552862.55,
      documents: [],
      effectiveDate: null,
      expiryDate: null,
      id: '96bc4b37-db28-40e9-8c5b-b52b94af0025',
      isPrimary: true,
      lease: null,
      mortgage: null,
      notationText: null,
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2725',
      rrrName: 'Crown Land',
      rrrParties: [
        {
          id: '6296096f-70bd-48f4-acb9-b48b8a8a0980',
          parties: [
            {
              address: {
                address1: '105 Wapiti Close',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 1E9',
                state: 'AB',
              },
              customMetadata: [],
              dob: null,
              email: 'sunlifefinancial@lac.gmail.com',
              familyName: null,
              forename: 'Sun Life Financial',
              gender: null,
              idReference: null,
              idType: 'National ID',
              partyId: 'PAR0439',
              partyType: 'Organisation',
              phone: '+1 506 0472760',
              profession: null,
              referenceNo: '18-708-2530',
              role: ['Agent', 'Multicipality', 'Attorney'],
            },
          ],
          share: null,
        },
        {
          id: '8a208ee3-fa66-4287-b6d2-2e021ebf4953',
          parties: [
            {
              address: {
                address1: '229A Three Sisters Drive',
                address2: 'Road 2',
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 0A1',
                state: 'AB',
              },
              customMetadata: [
                {
                  id: '32efdc95-ac9d-4239-82d7-95a94a8a4870',
                  metadata: { placeOfBirth: 'Jodon', serialNumber: null },
                },
              ],
              dob: null,
              email: 'matrox@lac.gmail.com',
              familyName: null,
              forename: 'Miami',
              gender: null,
              idReference: null,
              idType: 'Company Registration',
              partyId: 'PAR0297',
              partyType: 'Organisation',
              phone: '+1 506 4703912',
              profession: null,
              referenceNo: '95-670-72',
              role: ['Applicant'],
            },
          ],
          share: null,
        },
      ],
      status: 'HISTORIC',
    },
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [
        {
          id: '131a1a18-6797-4d3f-a272-f21c68f9ccd1',
          metadata: { twoServicesWereUsedOnWhichDay: null },
        },
      ],
      declaredValue: 200,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Contract between the first party and the second party for the purchase of this property',
          documentId: 'DOC0266',
          documentType: 'Contract for Sale',
          expiryDate: '1983-04-13',
          id: 'df86910b-90ff-456b-8d4a-577a4fa0bb91',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'MV/30/0977',
          signedDate: '1974-03-01',
          sourceAgency: 'BXOL & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '1.4',
        },
      ],
      effectiveDate: null,
      expiryDate: null,
      id: 'ab164f84-4cd8-4717-81d1-33dd2dff64e0',
      isPrimary: true,
      lease: null,
      mortgage: null,
      notationText:
        'Transfer of State Holding ownership to Sun Life Financial , Miami . Declared value of £200.00. Supporting documents: DOC0266.',
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2798',
      rrrName: 'State Holding',
      rrrParties: [
        {
          id: '715c5b01-36e0-47ed-ae7d-1f9949cc2d44',
          parties: [
            {
              address: {
                address1: '229A Three Sisters Drive',
                address2: 'Road 2',
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 0A1',
                state: 'AB',
              },
              customMetadata: [
                {
                  id: '32efdc95-ac9d-4239-82d7-95a94a8a4870',
                  metadata: { placeOfBirth: 'Jodon', serialNumber: null },
                },
              ],
              dob: null,
              email: 'matrox@lac.gmail.com',
              familyName: null,
              forename: 'Miami',
              gender: null,
              idReference: null,
              idType: 'Company Registration',
              partyId: 'PAR0297',
              partyType: 'Organisation',
              phone: '+1 506 4703912',
              profession: null,
              referenceNo: '95-670-72',
              role: ['Applicant'],
            },
            {
              address: {
                address1: '105 Wapiti Close',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 1E9',
                state: 'AB',
              },
              customMetadata: [],
              dob: null,
              email: 'sunlifefinancial@lac.gmail.com',
              familyName: null,
              forename: 'Sun Life Financial',
              gender: null,
              idReference: null,
              idType: 'National ID',
              partyId: 'PAR0439',
              partyType: 'Organisation',
              phone: '+1 506 0472760',
              profession: null,
              referenceNo: '18-708-2530',
              role: ['Agent', 'Multicipality', 'Attorney'],
            },
          ],
          share: null,
        },
      ],
      status: 'CURRENT',
    },
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: null,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Agreement between the first party and the second party for this registration entry',
          documentId: 'DOC0429',
          documentType: 'Agreement',
          expiryDate: '1945-04-22',
          id: '0bdf7dd3-05a5-4d7b-8a86-31879db9fc97',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'XE/88/6645',
          signedDate: '1939-05-08',
          sourceAgency: 'AHLY & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '3.0',
        },
      ],
      effectiveDate: null,
      expiryDate: null,
      id: '51e1373e-033f-4035-a744-6720ef4b6d9d',
      isPrimary: false,
      lease: null,
      mortgage: null,
      notationText:
        'Restriction of type Limited Access registered. Evidentiary evidence: DOC0429.',
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2760',
      rrrName: 'Limited Access',
      rrrParties: [],
      status: 'CURRENT',
    },
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: ['Development Timeframe'],
      customMetadata: [],
      declaredValue: null,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Lease agreement between this property owner and this third party',
          documentId: 'DOC0322',
          documentType: 'Lease',
          expiryDate: null,
          id: '12d3e342-e273-44f0-a19f-5b5cc98e49c6',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'ZT/12/5640',
          signedDate: '1955-01-16',
          sourceAgency: 'JMGT & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '2.5',
        },
      ],
      effectiveDate: '2023-07-02',
      expiryDate: '2023-07-31',
      id: 'bcfaf05b-d444-434a-9561-c71b1cccfd59',
      isPrimary: false,
      lease: { leaseId: 'LEA1214', payment: 500, paymentPeriod: 'ANNUALLY' },
      mortgage: null,
      notationText:
        'Lease (99 year) registered for  Sun Life Financial , Miami . Lease effective 7/02/2023, expiry 7/31/2023. Payment of £500.00, ANNUALLY. Lease document DOC0322.',
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2762',
      rrrName: 'Lease (99 year)',
      rrrParties: [
        {
          id: '4e7685d6-bb1b-47b6-88fb-8253c4e635a1',
          parties: [
            {
              address: {
                address1: '105 Wapiti Close',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 1E9',
                state: 'AB',
              },
              customMetadata: [],
              dob: null,
              email: 'sunlifefinancial@lac.gmail.com',
              familyName: null,
              forename: 'Sun Life Financial',
              gender: null,
              idReference: null,
              idType: 'National ID',
              partyId: 'PAR0439',
              partyType: 'Organisation',
              phone: '+1 506 0472760',
              profession: null,
              referenceNo: '18-708-2530',
              role: ['Agent', 'Multicipality', 'Attorney'],
            },
            {
              address: {
                address1: '229A Three Sisters Drive',
                address2: 'Road 2',
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 0A1',
                state: 'AB',
              },
              customMetadata: [
                {
                  id: '32efdc95-ac9d-4239-82d7-95a94a8a4870',
                  metadata: { placeOfBirth: 'Jodon', serialNumber: null },
                },
              ],
              dob: null,
              email: 'matrox@lac.gmail.com',
              familyName: null,
              forename: 'Miami',
              gender: null,
              idReference: null,
              idType: 'Company Registration',
              partyId: 'PAR0297',
              partyType: 'Organisation',
              phone: '+1 506 4703912',
              profession: null,
              referenceNo: '95-670-72',
              role: ['Applicant'],
            },
          ],
          share: null,
        },
      ],
      status: 'CURRENT',
    },
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: null,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Mortgage agreement between this rightholder bank and this property owner',
          documentId: 'DOC0441',
          documentType: 'Mortgage',
          expiryDate: null,
          id: 'db14b8c3-bf60-4f14-a881-34874f9db17a',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'HQ/52/7485',
          signedDate: '1964-01-29',
          sourceAgency: 'LBNM & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '2.4',
        },
      ],
      effectiveDate: '2023-07-02',
      expiryDate: '2023-07-31',
      id: 'fdf6f549-335d-46f1-8080-384f9a74bd61',
      isPrimary: false,
      lease: null,
      mortgage: { amount: 400, mortgageId: 'MOR1159' },
      notationText:
        'Registration of Mortgage (20 yr) for the amount of £400.00, given by Sun Life Financial , Miami , on 7/02/2023, expires 7/31/2023. Mortgage documents: DOC0441.',
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2763',
      rrrName: 'Mortgage (20 yr)',
      rrrParties: [
        {
          id: 'e4ef51b0-cc19-47db-8eb5-b2e2ffaa9349',
          parties: [
            {
              address: {
                address1: '229A Three Sisters Drive',
                address2: 'Road 2',
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 0A1',
                state: 'AB',
              },
              customMetadata: [
                {
                  id: '32efdc95-ac9d-4239-82d7-95a94a8a4870',
                  metadata: { placeOfBirth: 'Jodon', serialNumber: null },
                },
              ],
              dob: null,
              email: 'matrox@lac.gmail.com',
              familyName: null,
              forename: 'Miami',
              gender: null,
              idReference: null,
              idType: 'Company Registration',
              partyId: 'PAR0297',
              partyType: 'Organisation',
              phone: '+1 506 4703912',
              profession: null,
              referenceNo: '95-670-72',
              role: ['Applicant'],
            },
            {
              address: {
                address1: '105 Wapiti Close',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 1E9',
                state: 'AB',
              },
              customMetadata: [],
              dob: null,
              email: 'sunlifefinancial@lac.gmail.com',
              familyName: null,
              forename: 'Sun Life Financial',
              gender: null,
              idReference: null,
              idType: 'National ID',
              partyId: 'PAR0439',
              partyType: 'Organisation',
              phone: '+1 506 0472760',
              profession: null,
              referenceNo: '18-708-2530',
              role: ['Agent', 'Multicipality', 'Attorney'],
            },
          ],
          share: null,
        },
      ],
      status: 'CURRENT',
    },
    {
      applicationId: 'APP101676',
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: null,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description: 'Court order effecting transactions against this title',
          documentId: 'DOC10602',
          documentType: 'Court Order',
          expiryDate: '1944-04-10',
          id: '15774df4-077d-42f0-b1fa-560fe3758bb4',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'XX/42/7288',
          signedDate: '1934-11-11',
          sourceAgency: 'LBAG & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '2.9',
        },
      ],
      effectiveDate: null,
      expiryDate: null,
      id: 'e7e90b44-5fe7-4d56-bb19-a967d3847c7e',
      isPrimary: false,
      lease: null,
      mortgage: null,
      notationText: 'Court Order registered. Supporting documents: DOC10602.',
      registeredDate: '2023-07-20T11:56:28',
      rrrId: 'RRR2761',
      rrrName: 'Court Order',
      rrrParties: [],
      status: 'CURRENT',
    },
  ],
  status: 'HISTORIC',
  titleCorrections: [
    {
      correctedBy: 'jpeters',
      correctedParts: [
        {
          correctedObjectId: '0a000321-8972-1c6c-8189-73586c880005',
          correctionDetails: {
            appId: null,
            appLodgedDate: null,
            applicationId: 'APP101676',
            cadastreObjects: [],
            cancellationApplicationId: null,
            cancellationDocuments: [],
            cancellationNotationText: null,
            cancellationReason: null,
            cancellationSourceGeneratedIds: [],
            cancellationSourceIds: [],
            cancelledDate: null,
            cancelledRRRs: [],
            carryOverParentTitleId: null,
            correctionReason: null,
            createdBy: 'magma',
            createdDate: '2023-07-20T12:48:42',
            customMetadata: [
              {
                fieldGroupId: '67812e0f-1ed7-4b40-9a5a-4392762be288',
                id: '1e8a8cfe-11e7-4e05-b388-bbd4dc9e07ef',
                metadata: { textField: null },
                order: 1,
              },
            ],
            declaredValue: null,
            description: null,
            fileRef: null,
            hasLease: false,
            hasMortgage: false,
            hasRelationship: false,
            hasSecondaryRRR: false,
            hasTitleCorrected: false,
            id: '0a000321-8972-1c6c-8189-73586c880005',
            lastModifiedBy: 'magma',
            lastModifiedDate: '2023-07-20T11:56:28',
            lastModifiedOld: null,
            lastModifiedOldBy: null,
            legalFramework: null,
            legalTypeId: '9befb8e1-40b5-47d0-b50d-067eeb54231e',
            noAutoFill: false,
            notationText: null,
            parcelGeneratedId: null,
            parcelGeneratedIds: {
              '07f0deb7-3948-4e59-ada3-0f6d8203f7ff': 'PID13480',
            },
            parcelIds: ['07f0deb7-3948-4e59-ada3-0f6d8203f7ff'],
            parentTitleIds: null,
            parentToCancel: true,
            partyRelationships: [],
            pendingApplications: [],
            pendingCancellation: false,
            primaryRrr: null,
            registeredDate: '2023-07-20T11:56:28.621Z',
            resetAuditLog: false,
            rightHolderType: null,
            rrrs: [],
            serviceId: '8ea6a69d-cd29-4432-93d5-6baf5239cbb9',
            setLastModifiedDate: true,
            sourceGeneratedId: null,
            sourceIds: [],
            sources: [],
            status: 'CURRENT',
            tenant: null,
            titleCorrections: [],
            titleId: 'TID1193',
            titleRefId: 'TMP100679',
            toRelationships: [
              {
                appLodgedDate: null,
                createdBy: null,
                createdDate: '2023-07-20T12:48:42',
                id: '182f6b1d-b7c2-4a14-ab09-b155352f9eba',
                lastModifiedBy: null,
                lastModifiedDate: '2023-07-20T12:48:42',
                noAutoFill: false,
                relationshipTypeId: 'a350084d-91eb-4927-b77a-fae699a492cf',
                resetAuditLog: false,
                setLastModifiedDate: true,
              },
            ],
            validation: null,
          },
          correctionGeneratedId: 'TID1193',
          correctionType: 'TITLE_INFO',
          id: '76661608-895d-430f-906e-86a356b5e5aa',
        },
        {
          correctedObjectId: null,
          correctionDetails: null,
          correctionGeneratedId: null,
          correctionType: 'RRR',
          id: 'ad3b3a03-7ee0-42c8-a675-29788f5ac708',
        },
      ],
      correctionDate: '2023-07-22T07:42:09',
      correctionReason: 'test',
      id: 'd2e37d11-22ad-4721-8d24-eeac003273b3',
    },
  ],
  titleId: 'TID1193',
};
