export const jsonLeft = {
  applicationId: null,
  cancellationApplicationId: null,
  cancellationDocuments: [],
  cancellationNotationText: null,
  cancellationReason: null,
  cancelledDate: null,
  createdDate: '1948-08-24T10:42:53',
  customMetadata: [],
  description: null,
  documents: [],
  id: 'a75199ba-9fa2-46f5-93ec-0217ddf1b144',
  lastModifiedDate: '2023-06-18T16:28:30',
  legalFramework: 'Torrens',
  notationText: null,
  parcelGeneratedId: ['PID13106'],
  parentTitleIds: null,
  registeredDate: null,
  rrrs: [
    {
      applicationId: null,
      cancel: false,
      cancelledBY: {
        applicationId: 'APP1438',
        cancel: true,
        cancelledBY: null,
        conditionForRRR: [],
        customMetadata: [],
        declaredValue: null,
        documents: [
          {
            applicationId: null,
            checkSum: null,
            customMetadata: [],
            description:
              'Evidentiary proof that this right or restriction can be discharged',
            documentId: 'DOC0219',
            documentType: 'Discharge Notice',
            expiryDate: null,
            id: 'ebb703bb-422f-432a-aa56-4773b67e3553',
            isPoa: false,
            isStandardDocument: false,
            lodgedDate: null,
            powerOfAttorney: null,
            referenceNo: 'TJ/05/8086',
            signedDate: '1939-10-27',
            sourceAgency: 'DDSK & Co Ltd',
            sourceCorrectionLogDTOSet: [],
            version: '1.3',
          },
        ],
        effectiveDate: null,
        expiryDate: null,
        id: '44201612-9215-4f47-86d4-0b73aa2b458b',
        isPrimary: false,
        lease: null,
        mortgage: null,
        notationText: null,
        registeredDate: '2023-06-18T16:28:30',
        rrrId: 'RRR1732',
        rrrName: null,
        rrrParties: [],
        status: 'CANCELLATION',
      },
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: null,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Document supporting the legal varacity of this property transaction',
          documentId: 'DOC9781',
          documentType: 'Supporting Document',
          expiryDate: null,
          id: '6ea8d35a-3d9a-4397-916b-a0227466a233',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'NM/69/9414',
          signedDate: '1988-02-19',
          sourceAgency: 'MYJZ & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '1.6',
        },
      ],
      effectiveDate: null,
      expiryDate: null,
      id: '4c9717ce-c03c-4be8-b047-d912eb0677b9',
      isPrimary: false,
      lease: null,
      mortgage: null,
      notationText:
        'Restriction of Historic Preservation registered. Supporting documents: DOC9781',
      registeredDate: '1976-09-11T02:18:30',
      rrrId: 'RRR183410',
      rrrName: 'Historic Preservation',
      rrrParties: [],
      status: 'HISTORIC',
    },
    {
      applicationId: null,
      cancel: false,
      cancelledBY: null,
      conditionForRRR: [],
      customMetadata: [],
      declaredValue: 259361,
      documents: [
        {
          applicationId: null,
          checkSum: null,
          customMetadata: [],
          description:
            'Agreement between the first party and the second party for this registration entry',
          documentId: 'DOC7215',
          documentType: 'Agreement',
          expiryDate: '1987-01-10',
          id: '84d0a790-3c40-42c8-9467-4a2543d037c4',
          isPoa: false,
          isStandardDocument: false,
          lodgedDate: null,
          powerOfAttorney: null,
          referenceNo: 'HI/67/5944',
          signedDate: '1981-12-27',
          sourceAgency: 'TDHZ & Co Ltd',
          sourceCorrectionLogDTOSet: [],
          version: '1.4',
        },
      ],
      effectiveDate: null,
      expiryDate: null,
      id: 'c3406e03-6100-44bd-9c76-6b0cb1239b9c',
      isPrimary: true,
      lease: null,
      mortgage: null,
      notationText:
        'Transfer of Freehold ownership to Colin Fisher, Beatrice Woodward, Marion Lara. Declared value of $259,361.00. Supporting documents: DOC7215.',
      registeredDate: '1948-08-24T10:42:53',
      rrrId: 'RRR155588',
      rrrName: 'Freehold',
      rrrParties: [
        {
          id: '745d27b5-ec2f-4a33-8f59-60745eae9645',
          parties: [
            {
              address: {
                address1: '109 Carey',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 3A4',
                state: 'AB',
              },
              customMetadata: [],
              dob: '1985-05-18',
              email: 'marion.lara@lac.gmail.com',
              familyName: 'Lara',
              forename: 'Marion',
              gender: 'Male',
              idReference: null,
              idType: 'National ID',
              partyId: 'PAR3075',
              partyType: 'Individual',
              phone: '+1 506 0301888',
              profession: 'Truck driver',
              referenceNo: '53-138-61',
              role: ['Inheritor', 'Attorney'],
            },
            {
              address: {
                address1: '40 17th Street',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 1X7',
                state: 'AB',
              },
              customMetadata: [],
              dob: '1973-06-08',
              email: 'beatrice.woodward@lac.gmail.com',
              familyName: 'Woodward',
              forename: 'Beatrice',
              gender: 'Female',
              idReference: null,
              idType: 'Passport',
              partyId: 'PAR5402',
              partyType: 'Individual',
              phone: '+1 506 2263188',
              profession: 'Pupil',
              referenceNo: '57-853-30',
              role: ['Land Officer'],
            },
            {
              address: {
                address1: '122 Rundle Crescent',
                address2: null,
                city: 'Canmore',
                country: 'Canada',
                postalCode: 'T1W 0B5',
                state: 'AB',
              },
              customMetadata: [],
              dob: '1961-02-02',
              email: 'colin.fisher@lac.gmail.com',
              familyName: 'Fisher',
              forename: 'Colin',
              gender: 'Male',
              idReference: null,
              idType: 'Driving License',
              partyId: 'PAR1258',
              partyType: 'Individual',
              phone: '+1 506 9978454',
              profession: 'Tax collector',
              referenceNo: '49-944-81',
              role: ['Notary', 'Surveyor'],
            },
          ],
          share: null,
        },
      ],
      status: 'CURRENT',
    },
  ],
  status: 'CURRENT',
  titleCorrections: [],
  titleId: 'TID57848',
};
